### ISSUE TITLE
LP writer has wrong bounds for free variables

### ISSUE THREAD

**Issue by chengg04** [odow/MathOptFormat.jl#101]
When writing a model to an LP file, if a variable is free, the LP writer will not write any bound information into the file. However, by default if a variable has no bound in an LP file, it means the variable is nonnegative. For a minimum example, suppose we have the following minimization problem with free variables `gamma`s:
```
m = Model(with_optimizer(CPLEX.Optimizer))
@variable(m, gamma[i in 1:2])
@objective(m, Min, gamma[1] + gamma[2])
lp_file = MathOptFormat.LP.Model()
MOI.copy_to(lp_file, backend(m))
MOI.write_to_file(lp_file, "trivia_bug.lp")
```
JuMP produces the following lp file:
```
minimize
obj: 1 gamma_1_ + 1 gamma_2_
subject to
Bounds
End
```
If we solve this lp file with CPLEX, it will return an optimal value of 0. However, the problem should be unbounded.
The correct lp file should be:
```
minimize
obj: 1 gamma_1_ + 1 gamma_2_
subject to
Bounds
gamma_1_ Free
gamma_2_ Free
End
```

**Comment by odow** [comment]
Oops. This is totally my fault. Weird it wasn't noticed sooner.

**Comment by chengg04** [comment]
Guess it’s because not many people work with free variables :)

**Comment by odow** [comment]
I'll make a PR fixing this.

**Comment by odow** [comment]
p.s. @chengg04 This repository, MathOptFormat.jl, has been moved into the main MathOptInterface repository as the `FileFormats` submodule. 

Instead of 
```Julia
using MathOptFormat
const MOF = MathOptFormat

# use

using MathOptInterface
const MOF = MathOptInterface.FileFormats
```

**Comment by chengg04** [comment]
I see. Thanks!
