### ISSUE TITLE
Support for Unnamed Variables

### ISSUE THREAD

**Issue by ccoffrin** [odow/MathOptFormat.jl#18]
Would it be possible to support these?

**Comment by mlubin** [comment]
Names are used as identifiers in the file format (as in MPS and LP formats). That seems hard to work around, besides filling them in with arbitrary unique names.

**Comment by ccoffrin** [comment]
I am fine with arbitrary unique names.  For example `x_1:n` or the memory address of the VarRef would be fine by me.  You would probably also want an anonymous var flag, so these names could be discarded as the model was read back into memory.

**Comment by mlubin** [comment]
(Nit: Let's call them unnamed variables. Anonymous variables are a concept in JuMP that has a programming language connotation. An object with an empty string as a name is a different thing.)

**Comment by ccoffrin** [comment]
good point, totally agree.

**Comment by odow** [comment]
Leaving as a reminder. Steps to close this are:

1. address this TODO
https://github.com/odow/MathOptFormat.jl/blob/5cc68aaf6ce8ced40dc7cb1a5ad6494e45226173/src/write.jl#L58-L60

2. if a default name is detected, skip setting `MOI.VariableName` here:
https://github.com/odow/MathOptFormat.jl/blob/5cc68aaf6ce8ced40dc7cb1a5ad6494e45226173/src/read.jl#L26
