### ISSUE TITLE
ConicBenchmarkFormat conversion

### ISSUE THREAD

**Issue by chriscoey** [odow/MathOptFormat.jl#30]
Re: https://github.com/JuliaOpt/ConicBenchmarkUtilities.jl/pull/19

Would it make more sense to use MOF to access the CBF library (http://cblib.zib.de/) of conic problems from JuliaOpt, rather than trying to update and maintain ConicBenchmarkUtilities? We'd like to be able to both read and write CBF files (to contribute to CBLib).

**Comment by odow** [comment]
This seems reasonable.

**Comment by chriscoey** [comment]
Ok I can start working on this very soon. Can I just use the current MPS conversion code as a bit of a template?

**Comment by odow** [comment]
Yes. Basic steps
- Create a new submodule
https://github.com/odow/MathOptFormat.jl/blob/26157101d05698d9d542808a0a1a106727fd65a2/src/MPS/MPS.jl#L1
- Define a MOIU model with the functions/sets the format supports: 
https://github.com/odow/MathOptFormat.jl/blob/26157101d05698d9d542808a0a1a106727fd65a2/src/MPS/MPS.jl#L8-L19
- Implement `write_to_file`
https://github.com/odow/MathOptFormat.jl/blob/26157101d05698d9d542808a0a1a106727fd65a2/src/MPS/MPS.jl#L32
- Implement `read_from_file`
https://github.com/odow/MathOptFormat.jl/blob/26157101d05698d9d542808a0a1a106727fd65a2/src/MPS/MPS.jl#L397
