### ISSUE TITLE
Unable to install MathOptFormat on julia 1.0.3 

### ISSUE THREAD

**Issue by jmdvilela** [odow/MathOptFormat.jl#65]
I've been trying to install MathOptFormat, so I can use SDDP package, but I always end up with the same error (shown bellow). I'm using julia 1.0.3 on a windows machine and running `] add "https://github.com/odow/MathOptFormat.jl.git"`.

![image](https://user-images.githubusercontent.com/42416240/56809926-60d4d280-680b-11e9-9d08-47cf8ae8b2ec.png)

**Comment by odow** [comment]
Hmm. What is the output of
```julia
julia> versioninfo()
```

Are you on a network with a firewall? We need to download a JSON file from Github.

You could also try
```julia
julia> ] rm MathOptFormat

julia> ] add https://github.com/odow/MathOptFormat.jl
```

**Comment by jmdvilela** [comment]
Version Info:
![image](https://user-images.githubusercontent.com/42416240/56815177-0b9ebe00-6817-11e9-82d3-f5f723331860.png)

I tried what you suggested, but had no success. Got the same error

![image](https://user-images.githubusercontent.com/42416240/56815371-8ec01400-6817-11e9-9ce3-8df8166064e9.png)

**Comment by odow** [comment]
Can you show the full output of
```Julia
Julia> ] add MbedTLS
```

**Comment by jmdvilela** [comment]
just this

![image](https://user-images.githubusercontent.com/42416240/56817203-794ce900-681b-11e9-96fc-e513e4ce1f01.png)

**Comment by odow** [comment]
And what about
```julia
Julia> ] build MbedTLS
```

**Comment by jmdvilela** [comment]
didn't get any error

![image](https://user-images.githubusercontent.com/42416240/56818110-53c0df00-681d-11e9-93fe-86eba4ee0e60.png)

**Comment by odow** [comment]
Hmm. What files are in
```
C:\Users\jvilela\.julia\packages\MbedTLS\X4xar\deps\usr\downloads
```

**Comment by jmdvilela** [comment]
![image](https://user-images.githubusercontent.com/42416240/56818534-30e2fa80-681e-11e9-838f-2fe95700b254.png)

**Comment by odow** [comment]
Your machine is running 32bit Windows correct?

If it is actually 64bit, uninstall Julia, then download and install the 64 bit version of Julia https://julialang.org/downloads/

If it is 32 bit. Run
```Julia
Julia> ] rm MbedTLS
```
Then delete the `.Julia/packages/MbedTLS` folder, and then run
```Julia
Julia> ] add MbedTLS
```
Then check back to see that the `downloads` folder only contains the `i686` download, and not the `x86_64`.

**Comment by jmdvilela** [comment]
Actually, my machine is 64bit and that's the problem. Just download julia 64bit and it's working. Thank you for all the help

**Comment by odow** [comment]
Great that you got it working.
