### ISSUE TITLE
Easy-to-use interface?

### ISSUE THREAD

**Issue by dourouc05** [odow/MathOptFormat.jl#70]
Coming from JuMP 0.18-, when I see the interface that this package proposes, I think there is a large regression in user experience: a simple `writeLP(m, filename)` was all it took... Why not reviving the same interface in this package (which would supplement the existing one)? If you're OK with this idea, I can propose a PR for this (LP, MPS at least, maybe others?).

**Comment by odow** [comment]
Now that this package is registered, the way forward is to add it as a JuMP dependency, and then re-introduce the simple interface to JuMP.
