### ISSUE TITLE
Issues when installing MathOptFormat

### ISSUE THREAD

**Issue by spuschel** [odow/MathOptFormat.jl#77]
Hi,
I am trying to get the package to work in Julia 1.1.1 but I am having some type of odd interaction with the package HTTP. I tried downgrading packages, upgrading packages, with no luck. Please refer to the log below.

Any help is welcome, I need to debug a model built with JuMP and I need to print the LP.
Cheer
Sebastian

> (v1.1) pkg> add https://github.com/odow/MathOptFormat.jl
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
┌ Warning: Cannot perform fast-forward merge
└ @ LibGit2 /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/LibGit2/src/merge.jl:237
┌ Warning: Some registries failed to update:
│     — /Users/spuschel/.julia/registries/General — registry failed to rebase on origin/master
└ @ Pkg.Types /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:1269
  Updating git-repo `https://github.com/odow/MathOptFormat.jl`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package HTTP [cd3eb016]:
 HTTP [cd3eb016] log:
 ├─possible versions are: [0.0.1-0.0.2, 0.4.0-0.4.3, 0.5.0, 0.5.2-0.5.5, 0.5.7, 0.6.0-0.6.14, 0.7.0-0.7.1, 0.8.0] or uninstalled
 └─restricted to versions 0.8.2-* by MathOptFormat [f4570300] — no versions left
   └─MathOptFormat [f4570300] log:
     ├─possible versions are: 0.1.1 or uninstalled
     └─MathOptFormat [f4570300] is fixed to version 0.1.1

**Comment by odow** [comment]
What is the output of 
```Julia
] st
```

> ┌ Warning: Some registries failed to update:
│ — /Users/spuschel/.julia/registries/General — registry failed to rebase on origin/master
└ @ Pkg.Types /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:1269

This seems suspicious. But I don't know the cause.

**Comment by spuschel** [comment]
Hi, this is what I get:
> (v1.1) pkg> st
    Status `~/.julia/environments/v1.1/Project.toml`
  [ad839575] Blink v0.10.1
  [a076750e] CPLEX v0.4.4
  [336ed68f] CSV v0.4.3
  [49dc2e85] Calculus v0.4.1
  [34f1f09b] ClusterManagers v0.3.2
  [0fe7c1db] DataArrays v0.7.0
  [a93c6f00] DataFrames v0.17.1
  [31c24e10] Distributions v0.17.0
  [ffbed154] DocStringExtensions v0.7.0
  [c04bee98] ExcelReaders v0.11.0
  [2e9cd046] Gurobi v0.6.0
  [cd3eb016] HTTP v0.8.0
  [4076af6c] JuMP v0.19.0
  [b8f27783] MathOptInterface v0.8.4
  [fdba3010] MathProgBase v0.7.7
  [39abe10b] MySQL v0.7.0
  [2774e3e8] NLsolve v4.0.0
  [f0f68f2c] PlotlyJS v0.12.3
  [92933f4c] ProgressMeter v0.9.0
  [a8468747] QHull v0.0.1
  [f2b01f46] Roots v0.8.0
  [0aa819cd] SQLite v0.7.0
  [123dc426] SymEngine v0.5.0
  [ade2ca70] Dates 
  [8ba89e20] Distributed 
  [6462fe0b] Sockets

**Comment by odow** [comment]
It seems that `HTTP.jl` made an incorrect patch release, so we're stuck supporting `0.8.2`: https://github.com/JuliaWeb/HTTP.jl/issues/424
I'm guessing there is another package with an upper bound on HTTP. 

What happens if you go
```Julia
] add HTTP@0.8.4
] add MathOptFormat
```
Another work-around is to use different `Project`s instead of a single workspace. (Do you need all of those packages?)

This should do the trick:
```Julia
cd("a/path/to/my/new/workspace")
] activate .
] add JuMP
] add MathOptFormat
```

**Comment by spuschel** [comment]
Hi 
I tried both options with no luck. After creating a new environment, the first package I tried to install was MathOptFormat, and I got the same problems with HTTP, without it even being in the environment. I really don't understand what is going on. 
Cheers
Sebastian

> (jenvTEST) pkg> st
    Status `~/Documents/workspace/jenvTEST/Project.toml`
  (empty environment)

> (jenvTEST) pkg> add https://github.com/odow/MathOptFormat.jl
  Updating git-repo `https://github.com/odow/MathOptFormat.jl`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package HTTP [cd3eb016]:
 HTTP [cd3eb016] log:
 ├─possible versions are: [0.0.1-0.0.2, 0.4.0-0.4.3, 0.5.0, 0.5.2-0.5.5, 0.5.7, 0.6.0-0.6.14, 0.7.0-0.7.1, 0.8.0] or uninstalled
 └─restricted to versions 0.8.2-* by MathOptFormat [f4570300] — no versions left
   └─MathOptFormat [f4570300] log:
     ├─possible versions are: 0.1.1 or uninstalled
     └─MathOptFormat [f4570300] is fixed to version 0.1.1

**Comment by odow** [comment]
I can't reproduce this (see below). It's weird that your registry doesn't get updated. Try running `] up` before adding MathOptFormat.
```Julia
(base) dhcp-10-105-153-245:dni-evaluator oscar$ cd /tmp
(base) dhcp-10-105-153-245:tmp oscar$ mkdir MOF
(base) dhcp-10-105-153-245:tmp oscar$ cd MOF
(base) dhcp-10-105-153-245:MOF oscar$ julia --project=.
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(MOF) pkg> st
    Status `/private/tmp/MOF/Project.toml`
  (empty environment)

(MOF) pkg> activate .

(MOF) pkg> st
    Status `/private/tmp/MOF/Project.toml`
  (empty environment)

(MOF) pkg> add MathOptFormat
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed Parsers ─ v0.3.6
 Installed JSON ──── v0.21.0
  Updating `/private/tmp/MOF/Project.toml`
  [f4570300] + MathOptFormat v0.1.1
  Updating `/private/tmp/MOF/Manifest.toml`
  [b99e7846] + BinaryProvider v0.5.6
  [34da2185] + Compat v2.1.0
  [864edb3b] + DataStructures v0.17.0
  [92fee26a] + GZip v0.5.0
  [cd3eb016] + HTTP v0.8.4
  [83e8ac13] + IniFile v0.5.0
  [682c06a0] + JSON v0.21.0
  [7d188eb4] + JSONSchema v0.1.1
  [f4570300] + MathOptFormat v0.1.1
  [b8f27783] + MathOptInterface v0.8.4
  [739be429] + MbedTLS v0.6.8
  [bac558e1] + OrderedCollections v1.1.0
  [69de0a69] + Parsers v0.3.6
  [2a0f44e3] + Base64 
  [ade2ca70] + Dates 
  [8bb1440f] + DelimitedFiles 
  [8ba89e20] + Distributed 
  [b77e0a4c] + InteractiveUtils 
  [76f85450] + LibGit2 
  [8f399da3] + Libdl 
  [37e2e46d] + LinearAlgebra 
  [56ddb016] + Logging 
  [d6f4376e] + Markdown 
  [a63ad114] + Mmap 
  [44cfe95a] + Pkg 
  [de0858da] + Printf 
  [3fa0cd96] + REPL 
  [9a3f8284] + Random 
  [ea8e919c] + SHA 
  [9e88b42a] + Serialization 
  [1a1011a3] + SharedArrays 
  [6462fe0b] + Sockets 
  [2f01184e] + SparseArrays 
  [10745b16] + Statistics 
  [8dfed614] + Test 
  [cf7118a7] + UUIDs 
  [4ec0a83e] + Unicode 

(MOF) pkg> st
    Status `/private/tmp/MOF/Project.toml`
  [f4570300] MathOptFormat v0.1.1

(MOF) pkg> add JuMP
 Resolving package versions...
  Updating `/private/tmp/MOF/Project.toml`
  [4076af6c] + JuMP v0.19.2
  Updating `/private/tmp/MOF/Manifest.toml`
  [9e28174c] + BinDeps v0.8.10
  [49dc2e85] + Calculus v0.5.0
  [bbf7d656] + CommonSubexpressions v0.2.0
  [163ba53b] + DiffResults v0.0.4
  [b552c78f] + DiffRules v0.0.10
  [f6369f11] + ForwardDiff v0.10.3
  [4076af6c] + JuMP v0.19.2
  [77ba4419] + NaNMath v0.3.2
  [276daf66] + SpecialFunctions v0.7.2
  [90137ffa] + StaticArrays v0.11.0
  [30578b45] + URIParser v0.4.0

(MOF) pkg> st
    Status `/private/tmp/MOF/Project.toml`
  [4076af6c] JuMP v0.19.2
  [f4570300] MathOptFormat v0.1.1

julia> 
```

**Comment by spuschel** [comment]
I tried running up before installing your package, but I get the same error related to HTTP. Can this be a platform-specific issue? Please let me know if you think of a way to debug this problem.
Thanks 
Cheers

**Comment by odow** [comment]
Did you try installing it in a new project like I did above?

**Comment by odow** [comment]
Closing as stale. Please re-open if you still can't install it.
