### ISSUE TITLE
Export runs smoothly but returns corrupted file when variable base name includes a blank

### ISSUE THREAD

**Issue by mstriebs** [odow/MathOptFormat.jl#78]
When the base name of a variable includes a blank the export runs smoothly however the exported model (in this case to .mps)  is corrupted and cannot be used either in other tools, or reimported into julia

This Works just fine
```julia
using JuMP, Gurobi, MathOptFormat
model = Model(with_optimizer(Gurobi.Optimizer));
t = [1,2,3]
@variable(model, aVar[t] >= 0,  base_name="aVar");
@variable(model, OBJ[t],  base_name="Obj");
@constraint(model,[T=t], OBJ[T] == aVar[T]*3 );
@constraint(model,[T=t], aVar[T] <= T-1);
@objective(model, Max, sum(OBJ[T] for T in t))
optimize!(model)

# Export
mps_model = MathOptFormat.MPS.Model()
MOI.copy_to(mps_model, backend(model))
MOI.write_to_file(mps_model, "ModelForTest.mps")

# Import
mathoptformat_model = MathOptFormat.MPS.Model()
MOI.read_from_file(mathoptformat_model, "ModelForTest.mps")
```

Now just add a blank into the variable name aVar -> "a Var"
```julia
using JuMP, Gurobi, MathOptFormat
model = Model(with_optimizer(Gurobi.Optimizer));
t = [1,2,3]
@variable(model, aVar[t] >= 0,  base_name="a Var");
@variable(model, OBJ[t],  base_name="Obj");
@constraint(model,[T=t], OBJ[T] == aVar[T]*3 );
@constraint(model,[T=t], aVar[T] <= T-1);
@objective(model, Max, sum(OBJ[T] for T in t))
optimize!(model)

# Export
mps_model = MathOptFormat.MPS.Model()
MOI.copy_to(mps_model, backend(model))
MOI.write_to_file(mps_model, "ModelForTest.mps")

# Import
mathoptformat_model = MathOptFormat.MPS.Model()
MOI.read_from_file(mathoptformat_model, "ModelForTest.mps")
```
The code fails at MOI.read_from_file returning the error message 
"ERROR: Malformed COLUMNS line: a Var[2] c8 1"

Update:
I tried it with these sepcial characters "!§%&/()={[]}-_.,;:><" and all pose no problem. It's only the blank

**Comment by odow** [comment]
Thanks for this report. The way to fix it is to modify `create_unique_names` to accept `replacements`
```Julia
function create_unique_names(model::MOI.ModelLike; warn::Bool=false, replacements::Vector{Pair{Char, Char}})
```
and then [update the logic in these functions](https://github.com/odow/MathOptFormat.jl/blob/39048ec3d50153b38992f8a6b38a60396fa3433a/src/MathOptFormat.jl#L52-L141) to loop through the `replacements` and call `replace(name, replacement)` on the name.

Then, in
https://github.com/odow/MathOptFormat.jl/blob/39048ec3d50153b38992f8a6b38a60396fa3433a/src/MPS/MPS.jl#L59
we can add
```Julia
create_unique_names(model, warn = options.warn, replacements = [' ' => '_'])
