### ISSUE TITLE
Add SDPA

### ISSUE THREAD

**Issue by odow** [odow/MathOptFormat.jl#79]
Links:

- https://github.com/JuliaOpt/SemidefiniteOptInterface.jl/blob/29115f10bdf66526e1b9d12346c450790632a758/src/sdpa.jl
- http://plato.asu.edu/ftp/sdpa_format.txt

**Comment by ericphanson** [comment]
Just to say, @JiazhengZhu wrote some code over at SDPA-GMP which might be useful: https://github.com/ericphanson/SDPA_GMP.jl/blob/master/src/file_io.jl. SDPA-GMP (and -DD and -QD) only compile to a binary (not a library), so in SDPA-GMP.jl we need to write problems to files and read the results.

**Comment by blegat** [comment]
I'll have a try
